// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AsyncInnContext))]
    [Migration("20230731072017_DB1")]
    partial class DB1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Amenity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Amenity");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "A/C"
                        },
                        new
                        {
                            ID = 2,
                            Name = "A/C"
                        },
                        new
                        {
                            ID = 3,
                            Name = "A/C"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.HotelLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HotelLocation");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "1236 rode",
                            City = "midtown",
                            Name = "laaBy",
                            PhoneNumber = "555-555-5555",
                            State = "TN"
                        },
                        new
                        {
                            ID = 2,
                            Address = "7891 rode",
                            City = "hightown",
                            Name = "Nigth 9",
                            PhoneNumber = "666-666-6666",
                            State = "TN"
                        },
                        new
                        {
                            ID = 3,
                            Address = "1112 rode",
                            City = "lowtown",
                            Name = "Layback Bay",
                            PhoneNumber = "777-777-7777",
                            State = "TN"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LayoutType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelLocationID")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetFriendly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LayoutType = "large",
                            HotelLocationID = 1,
                            Nickname = "pro",
                            PetFriendly = "yes",
                            Price = 150.0
                        },
                        new
                        {
                            ID = 2,
                            LayoutType = "mid",
                            HotelLocationID = 2,
                            Nickname = "Basic Double",
                            PetFriendly = "yes",
                            Price = 100.0
                        },
                        new
                        {
                            ID = 3,
                            LayoutType = "small",
                            HotelLocationID = 3,
                            Nickname = "Basic Single",
                            PetFriendly = "no",
                            Price = 50.0
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.RoomAmenity", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("AmenityID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.ToTable("RoomAmenity");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            AmenityID = 1,
                            Description = "cool"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
